runtime: nodejs18

instance_class: F2

automatic_scaling:
  max_instances: 1

handlers:
  - url: /.*
    secure: always
    script: auto

env_variables:
  HOST: '0.0.0.0'
  NEXT_PUBLIC_BASE_URL: 'http://localhost:3000'
  NEXT_PUBLIC_API_BASE_URL: 'http://localhost:3000/api/jhipster-mocks'
  NEXT_PUBLIC_DEV_ENV_NAME: 'staging'
  NEXT_PUBLIC_DEV_ENV_COLOR_SCHEME: 'teal'
  DATABASE_URL: 'file:./dev.db'
  AUTH_SECRET: 'Replace me with `openssl rand -base64 32` generated secret'
  NEXT_PUBLIC_IS_DEMO: 'false'
