name: 'Deploy TurboRepo app to Google App Engine'
description: 'Deploy TurboRepo Apps to Google App Engine using a flexible nodejs runtime and npm.'
author: Céline Louvet
branding:
  color: 'purple'
  icon: 'briefcase'

inputs:
  gcloud_project_id:
    description: ID of the Google Cloud project.
    required: true

  gcloud_credentials_json:
    description: Service account key used to authenticate with Google Cloud.
    required: true

  env:
    description: staging or prod
    required: true

  should_promote:
    description: Whether to promote the app and route all traffic to the new version.
    required: false
    default: 'false'

  target_app:
    description: App name to deploy
    required: true

  target_service:
    description: Service name to deploy
    required: false
    default: 'default'

  apps_directory:
    description: Folder name containing the apps
    default: apps
    required: false

  test_endpoint:
    description: This endpoint will be called (GET) after deployment. For example, "/test"
    required: true

outputs:
  version_url:
    description: URL of the new version deployed
    value: ${{ steps.deploy.outputs.version_url }}

runs:
  using: 'composite'
  steps:
    - name: Simplify monorepo to ${{inputs.target_app}}
      shell: bash
      run: npx turbo prune --scope=${{ inputs.target_app }}

    - name: Add out dir from turbo prune to env
      shell: bash
      run: echo "OUT=${{ github.workspace }}/out" >> $GITHUB_ENV

    - name: Install dependencies
      shell: bash
      run: npm install
      working-directory: out

    - name: Build app
      shell: bash
      run: npx turbo ${{ inputs.target_app }}#build
      working-directory: out

    - name: Checks
      shell: bash
      run: node ${{ github.action_path }}/src/checks.mjs --folder=$OUT

    - name: Define working directory
      shell: bash
      run: echo "TARGET_DIRECTORY=$OUT/${{ inputs.apps_directory }}/${{ inputs.target_app }}" >> $GITHUB_ENV

    - name: Define package name
      shell: bash
      run: echo "PACKAGE_NAME=$(jq -r '.name' $TARGET_DIRECTORY/package.json)" >> $GITHUB_ENV

    - name: Overwrite $OUT/package.json
      shell: bash
      run: node ${{ github.action_path }}/src/overwritePackages.mjs --folder=$OUT

    - name: Prepare $OUT/.gcloudignore
      shell: bash
      run: node ${{ github.action_path }}/src/createGcloudIgnore.mjs --folder=$OUT

    - name: Prepare $OUT/app.yaml
      shell: bash
      run: node ${{ github.action_path }}/src/createAppFile.mjs --folder=$OUT --env=staging --version=${{ github.ref_name }} --service=${{inputs.target_service}}

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v2
      with:
        project_id: ${{ inputs.gcloud_project_id }}
        credentials_json: ${{ inputs.gcloud_credentials_json }}

    - id: deploy
      name: Deploy to GCP AppEngine
      uses: google-github-actions/deploy-appengine@v2
      env:
        CLOUDSDK_APP_CLOUD_BUILD_TIMEOUT: 1800 # 30 minutes
      with:
        project_id: ${{ inputs.gcloud_project_id }}
        deliverables: app.yaml
        promote: ${{inputs.should_promote}}
        version: ${{ github.ref_name }}
        working_directory: out

    - id: test
      name: Test deployed version
      run: node ${{ github.action_path }}/src/testDeployment.mjs --testUrl=${{ steps.deploy.outputs.version_url }}${{ inputs.test_endpoint }}
      shell: bash

    - name: Clean
      shell: bash
      run: rm -fr $OUT
