name: cd-appengine

on:
  push:
    branches:
      - main

env:
  GCP_DOMAIN: "https://celine.louvet.me"
  PDF_FILE: "LOUVET_Celine.pdf"
  IMAGE_FILE: "LOUVET_Celine.png"

jobs:
  deploy:
    name: Deploy
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn && cd pdf-generator && yarn

      - name: Generate
        run: yarn generate

      - id: auth
        name: Auth to GCP
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - id: deploy
        name: Deploy to GCP AppEngine
        uses: google-github-actions/deploy-appengine@v0
        with:
          deliverables: app.yaml
          promote: true
          version: v1

      - name: Test default URL
        run: curl --silent --head "${{ steps.deploy.outputs.url }}"

      - name: Test ${{ env.GCP_DOMAIN }} URL
        run: curl --silent --head "${{ env.GCP_DOMAIN }}"

  pdf:
    name: Generate PDF
    needs: deploy
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Generate PDF
        run: cd pdf-generator && yarn && yarn pdf --pdf "${{ env.PDF_FILE }}" --pageUrl "${{ env.GCP_DOMAIN }}"

      - id: auth
        name: Auth to GCP
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Upload FR PDF CV
        uses: google-github-actions/upload-cloud-storage@v0
        with:
          path: "./pdf-generator/fr_${{ env.PDF_FILE }}"
          destination: celinelouvet-cv.appspot.com/CV/
          predefinedAcl: publicRead

      - name: Upload EN PDF CV
        uses: google-github-actions/upload-cloud-storage@v0
        with:
          path: "./pdf-generator/en_${{ env.PDF_FILE }}"
          destination: celinelouvet-cv.appspot.com/CV/
          predefinedAcl: publicRead

      
