name: ci-appengine

on:
  push:
    branches-ignore:
      - 'v3'
      - 'v2**'
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.job }}
  cancel-in-progress: true

env:
  VERSION: ${{ github.ref_name }}
  PDF_FILE: 'LOUVET_Celine'
  BUCKET_NAME: '${{ vars.GCP_PROJECT }}.appspot.com'
  FORCE_COLOR: true

jobs:
  deploy:
    name: Deploy
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [22]

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node env
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Cache node modules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Install dependencies
        run: npm ci

      - name: Clean
        run: npm run clean

      - name: Build packages
        run: |
          npx turbo @repo/eslint-config#build
          npx turbo @repo/jest-presets#build
          npx turbo @repo/typescript-config#build
          npx turbo @repo/models#build

      - name: Build apps
        run: |
          npx turbo api#build
          npx turbo website#build

      - name: Typechecks
        run: npm run typecheck

      - name: Lint code and types
        run: npm run lint

      - id: deploy_website
        name: Deploy website to GCP AppEngine
        uses: ./.github/actions/turbo-deploy-gae
        with:
          apps_directory: apps
          target_app: website
          env: staging
          test_endpoint: /test
          gcloud_project_id: ${{ vars.GCP_PROJECT }}
          gcloud_credentials_json: ${{ secrets.GCP_SA_KEY }}
          should_promote: false

      - id: deploy_api
        name: Deploy api to GCP AppEngine
        uses: ./.github/actions/turbo-deploy-gae
        with:
          apps_directory: apps
          target_app: api
          target_service: api
          env: staging
          test_endpoint: /test
          gcloud_project_id: ${{ vars.GCP_PROJECT }}
          gcloud_credentials_json: ${{ secrets.GCP_SA_KEY }}
          should_promote: false

    outputs:
      versionUrl: ${{ steps.deploy_website.outputs.version_url }}

  slidePdf:
    name: Generate Slides PDF
    needs: deploy
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [22]
        talkSubjectId: [highway-to-fail, choice-must-go-on]

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Define bucket path
        id: bucket
        run: echo "BUCKET_PATH=${{env.BUCKET_NAME}}/${{ env.VERSION }}/slides" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node env
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Cache node modules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - id: auth
        name: Auth to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Install dependencies
        run: npm ci

      - name: Generate PDF
        shell: bash
        run: npx turbo run slides --  --pageUrl="${{ env.VERSION_URL }}" --talkSubjectId="${{ env.TALK_SUBJECT_ID }}" --out="_generated"
        env:
          VERSION_URL: ${{ needs.deploy.outputs.versionUrl }}
          TALK_SUBJECT_ID: ${{ matrix.talkSubjectId }}

      - name: Upload PDF
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: tools/slides-generator/_generated
          destination: ${{ steps.bucket.outputs.BUCKET_PATH }}
          parent: false
          glob: '**/*.pdf'
          predefinedAcl: publicRead
          process_gcloudignore: false

  resumePdf:
    name: Generate Resume PDF
    needs: deploy
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [22]

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Define bucket path
        id: bucket
        run: echo "BUCKET_PATH=${{env.BUCKET_NAME}}/${{ env.VERSION }}/resume" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node env
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Cache node modules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - id: auth
        name: Auth to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Install dependencies
        run: npm ci

      - name: Generate PDF
        shell: bash
        run: npx turbo run resume --  --pageUrl="${{ env.VERSION_URL }}" --out="_generated"
        env:
          VERSION_URL: ${{ needs.deploy.outputs.versionUrl }}

      - name: Upload PDF
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: tools/resume-generator/_generated
          destination: ${{ steps.bucket.outputs.BUCKET_PATH }}
          parent: false
          glob: '**/*.pdf'
          predefinedAcl: publicRead
          process_gcloudignore: false

      - name: Upload screenshots
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: tools/resume-generator/_generated
          destination: ${{ steps.bucket.outputs.BUCKET_PATH }}
          parent: false
          glob: '**/*.png'
          predefinedAcl: publicRead
          process_gcloudignore: false
