name: ci-appengine

on:
  push:
    branches-ignore:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  VERSION: ${{ github.ref_name }}
  PDF_FILE: "LOUVET_Celine"
  BUCKET_NAME: "celinelouvet-cv.appspot.com"

jobs:
  deploy:
    name: Deploy
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]

    permissions:
      contents: read
      id-token: write

    outputs:
      url: ${{ steps.deploy.outputs.url }}

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn && cd pdf-generator && yarn

      - name: Lint
        run: yarn lint

      - name: Generate
        run: yarn generate

      - id: auth
        name: Auth to GCP
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - id: deploy
        name: Deploy to GCP AppEngine
        uses: google-github-actions/deploy-appengine@v0
        with:
          deliverables: app.yaml
          promote: false
          version: ${{ env.VERSION }}

      - name: Test deployed version
        run: curl --silent --head "${{ steps.deploy.outputs.url }}"

  pdf:
    name: Generate PDF
    needs: deploy
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Define bucket path
        run: echo "BUCKET_PATH=${{env.BUCKET_NAME}}/${{ env.VERSION }}/resume" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Generate PDF
        run: cd pdf-generator && yarn && yarn pdf --pdf "${{ env.PDF_FILE }}" --pageUrl "${{needs.deploy.outputs.url}}"

      - id: auth
        name: Auth to GCP
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Upload FR PDF Resume
        uses: google-github-actions/upload-cloud-storage@v0
        with:
          path: "./pdf-generator/${{ env.PDF_FILE }}_FR.pdf"
          destination: ${{ env.BUCKET_PATH }}
          predefinedAcl: publicRead

      - name: Upload EN PDF Resume
        uses: google-github-actions/upload-cloud-storage@v0
        with:
          path: "./pdf-generator/${{ env.PDF_FILE }}_EN.pdf"
          destination: ${{ env.BUCKET_PATH }}
          predefinedAcl: publicRead
