name: ci

on:
  push:
    branches-ignore:
      - main

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  Lint:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn && cd pdf-generator && yarn

      - name: Lint
        run: yarn lint

      - name: Generate
        run: yarn generate
